name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Restore dependencies
      run: dotnet restore mojoportal.sln
    - name: Build
      run: msbuild mojoportal.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal 
