name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '5.x'
    - name: Restore Packages
      run: nuget restore mojoPortal.sln
    - name: Restore dependencies
      run: dotnet restore mojoPortal.sln
    - name: Build
      run: msbuild mojoPortal.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal 
